#version: '3.7'
services:
  screw_detection:
    build:
      context: .
      dockerfile: Dockerfile
    image: screw_detection:latest
    volumes:
      - C:\Users\risha\Documents\Rishabh_Project:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- $SSH_AUTH_SOCK:/ssh-agent
      - ~/.Xauthority:/root/.Xauthority
      - ~/.gitconfig:/etc/gitconfig
    network_mode: host
    privileged: true
    container_name: screw_detection_container
    environment:
      DISPLAY: 172.18.240.1:0.0
      NAMESPACE: $NAMESPACE
    #command:
    #  - /bin/bash
    #  - -c
    #  - "python3 /project/scripts/predict_screw_pose.py"
    tty: true
